--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)


--
-- Name: zone; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS zone;




--
-- Name: template_records; Type: TABLE; Schema: zone; Owner: -
--

CREATE TABLE zone.template_records (
    recordid bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(10) NOT NULL,
    content character varying(65535) NOT NULL,
    ttl integer DEFAULT 3600 NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    templateid bigint NOT NULL
);


--
-- Name: template_records_recordid_seq; Type: SEQUENCE; Schema: zone; Owner: -
--

ALTER TABLE zone.template_records ALTER COLUMN recordid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zone.template_records_recordid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: templates; Type: TABLE; Schema: zone; Owner: -
--

CREATE TABLE zone.templates (
    templateid bigint NOT NULL,
    customerid bigint,
    name character varying(255) NOT NULL,
    description character varying(255) DEFAULT ''::character varying NOT NULL
);


--
-- Name: templates_templateid_seq; Type: SEQUENCE; Schema: zone; Owner: -
--

ALTER TABLE zone.templates ALTER COLUMN templateid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME zone.templates_templateid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: templates domain_templates_pk; Type: CONSTRAINT; Schema: zone; Owner: -
--

ALTER TABLE ONLY zone.templates
    ADD CONSTRAINT domain_templates_pk PRIMARY KEY (templateid);


--
-- Name: template_records template_records_pk; Type: CONSTRAINT; Schema: zone; Owner: -
--

ALTER TABLE ONLY zone.template_records
    ADD CONSTRAINT template_records_pk PRIMARY KEY (recordid);


--
-- Name: customerid_idx; Type: INDEX; Schema: zone; Owner: -
--

CREATE INDEX customerid_idx ON zone.templates USING btree (customerid);


--
-- Name: template_records templateid_fk; Type: FK CONSTRAINT; Schema: zone; Owner: -
--

ALTER TABLE ONLY zone.template_records
    ADD CONSTRAINT templateid_fk FOREIGN KEY (templateid) REFERENCES zone.templates(templateid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
